### ISSUE TITLE
Feature request: automatically download lyrics if not found locally

### ISSUE THREAD

**Issue by yuygfgg** [flc0105/Lyrics#1]
When lyrics is missing in folder, current version shows "lyric not found".  Is it possible to download the first in search lyrics box automaticlly?

**Comment by yuygfgg** [comment]
I've solved it myself. [here](https://github.com/yuygfgg/Lyrics)

**Comment by flc0105** [comment]
我自己用的时候没有考虑自动搜索的功能，因为考虑到歌词自动匹配的准确性，有的同名音乐还会出现在不同专辑里，我看了下你做了一个按播放时长来过滤，也是个不错的思路。

**Comment by flc0105** [comment]
@yuygfgg
